<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Class Library produces a .dll artifact -->
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>MathLibrary</AssemblyName>
    <RootNamespace>MathLibrary</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
  </PropertyGroup>

</Project>
