<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Console executable -->
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>HelloApp</AssemblyName>
    <RootNamespace>HelloApp</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
  </PropertyGroup>

</Project>
